services:
  - type: web
    name: lahari-portfolio
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: MAIL_USERNAME
        sync: false
      - key: MAIL_PASSWORD
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: PORT
        value: 5000
